# Generated by Django 4.0.4 on 2022-06-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='time',
            new_name='timestamp',
        ),
    ]
