# Generated by Django 4.0.4 on 2022-06-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=40)),
                ('user_lname', models.CharField(max_length=40)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
