# Generated by Django 4.0.4 on 2022-06-01 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
