# Generated by Django 4.0.4 on 2022-06-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
